Fix QTimer.currentTime() AttributeError in GUI
- Changed QTimer.currentTime() to QTime.currentTime()
- QTimer is for scheduling, QTime is for time values
- Added missing 'time' module import for uptime tracking
- Fixes crash when clicking 'Start System' button

Error was:
  AttributeError: type object 'QTimer' has no attribute 'currentTime'

Resolution:
  Import QTime from PyQt5.QtCore and use QTime.currentTime()